horizontal_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: horizontal_joint
    joint_speed: 0.3
    motor:
        id: 2 
        init: 512
        min: 0
        max: 1023

vertical_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: vertical_joint
    joint_speed: 0.3
    motor:
        id: 1 
        init: 512
        min: 0
        max: 1023
